

services:
  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
  bot:
    build: .
    command: python -m app.bot.main
    depends_on:
      - app
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
      - db

  db:
    image: postgres:15  # Используйте желаемую версию PostgreSQL
    restart: always
    environment:
      POSTGRES_USER: myuser       # Имя пользователя PostgreSQL
      POSTGRES_PASSWORD: mypassword   # Пароль пользователя PostgreSQL
      POSTGRES_DB: mydb           # Имя базы данных
    ports:
      - "5432:5432"  # Отобразите порт 5432 (стандартный порт PostgreSQL)
    volumes:
      - db_data:/var/lib/postgresql/data  # Примонтируйте том для хранения данных
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ["postgres", "-c", "shared_preload_libraries=pg_trgm"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 1s
      timeout: 120s
      retries: 5
volumes:  
  db_data:
